name: 构建并推送镜像到 AWS 中国区 ECR  
on:  
  push:  
    branches:  
      - main  
  workflow_dispatch:   


jobs:  
  build-push-ecr:  
    runs-on: ubuntu-latest  
    steps:  
      - name: 检出代码  
        uses: actions/checkout@v4  

      - name: 构建 Docker 镜像  
        run: |  
          docker build -t my-local-image:${{ github.sha }} .  

      - name: 推送镜像到 AWS 中国区 ECR  
        id: ecr-push  
        uses: jwalton/gh-ecr-push@v2  
        with:  
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
          region: cn-northwest-1  # 与 ECR 仓库区域一致  
          local-image: my-local-image:${{ github.sha }}  
          image: 500953614955.dkr.ecr.cn-northwest-1.amazonaws.com.cn/devops/thumbnailpicture:${{ github.sha }}, 500953614955.dkr.ecr.cn-northwest-1.amazonaws.com.cn/devops/thumbnailpicture:latest  
          # 关键：地址包含 .amazonaws.com.cn 后缀，仓库名 devops/thumbnailpicture 需与 ECR 一致  

      - name: 输出镜像地址  
        run: |  
          echo "镜像地址: ${{ steps.ecr-push.outputs.imageUrl }}"
